function [dy] = modellbalken5singdgl(s, y, parameters)
%modellbalken5dgl: Differentialgleichungen für stetigen Modellbalken
global q;
p=parameters(1);
phi=y(3);
dy=[cos(phi); sin(phi); -y(4); y(5)*cos(phi)+p*sin(phi); -q;...
        -sin(phi)*y(8);...
        cos(phi)*y(8);...
        -y(9);...
        y(10)*cos(phi)+(-y(5)*sin(phi)+p*cos(phi))*y(8);...
        0];
end